SELECT 
    [Extent1].[IdTalento] AS [IdTalento], 
    [Extent1].[NomeTalento] AS [NomeTalento], 
    [Extent1].[EmailTalento] AS [EmailTalento], 
    [Extent1].[CidadeTalento] AS [CidadeTalento], 
    [Extent1].[TelefoneTalento] AS [TelefoneTalento], 
    [Extent1].[LinkedinTalento] AS [LinkedinTalento], 
    [Extent1].[SkypeTalento] AS [SkypeTalento], 
    [Extent1].[EstadoTalento] AS [EstadoTalento], 
    [Extent1].[PortifolioTalento] AS [PortifolioTalento], 
    [Extent1].[DisponibilidadeTalento] AS [DisponibilidadeTalento], 
    [Extent1].[HorarioTalento] AS [HorarioTalento], 
    [Extent1].[PretencaoTalento] AS [PretencaoTalento], 
    [Extent1].[NomeTalentoBanco] AS [NomeTalentoBanco], 
    [Extent1].[AgenciaTalento] AS [AgenciaTalento], 
    [Extent1].[CpfTalento] AS [CpfTalento], 
    [Extent1].[ContaTalento] AS [ContaTalento], 
    [Extent1].[BancoTalento] AS [BancoTalento], 
    [Extent1].[TipoContaTalento] AS [TipoContaTalento], 
    [Extent1].[OutroConhecimentoTalento] AS [OutroConhecimentoTalento], 
    [Extent1].[CrudTalento] AS [CrudTalento]
    FROM [dbo].[Talento] AS [Extent1]